#!/usr/bin/env python
# _*_ coding: utf-8 _*_
"""week 5 extra credit"""

import copy

var1 = [1,2,3,4,5]
var2 = copy.deepcopy(var1)
var2.extend([6,7,8])

print var1
print var2

var3 = [3,4,5,6,7]
var4 = var3
var4.extend([8,9,10])

print var3
print var4
